### PR TITLE
Module/emulandice2

### PR DESCRIPTION
**Pull request by AlexReedy**
This addresses issue https://github.com/radical-collaboration/facts/issues/315 as well as corrects the pipelines for the new(ish) build files.

### CODE REVIEW

**Comment by bobkopp** [comment]
@AlexReedy do we have plots to inspect?

**Comment by AlexReedy** [comment]
emulandice2_ais_global
emulandice2_glaciers_global
emulandice2_gris_global

**Comment by bobkopp** [comment]
@AlexReedy time series plots, though? Of the median, 17th, 83rd percentile projections to 2150 and 2300 under both pipelines, extrapolating 2080-2100 for the 2100 pipeline for GrIS and glaciers.

**Comment by AlexReedy** [comment]
Oh! Not yet, will get those

**Review by bobkopp — APPROVED** [review]

**Pull request merged**
